CREATE TABLE Users (
  id SERIAL PRIMARY KEY,
  login VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  age INTEGER,
  isDeleted BIT
);

INSERT INTO Users
VALUES ("1","test01@gmail.com","password1",18, 0)
INSERT INTO Users
VALUES ("2","test02@gmail.com","password2",19, 0)
INSERT INTO Users
VALUES ("3","test03@gmail.com","password3",20, 0)
INSERT INTO Users
VALUES ("4","test04@gmail.com","password4",21, 0)

CREATE TABLE Groups (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR ( 255 ) CHECK(name !='') NOT NULL,
	permissions TEXT[] CHECK(permissions <@ ARRAY['READ', 'WRITE', 'DELETE', 'SHARE', 'UPLOAD_FILES']) NOT NULL
);

INSERT INTO Groups (name, permissions) VALUES ('group1', ARRAY['READ','DELETE', 'WRITE']);
INSERT INTO Groups (name, permissions) VALUES ('group2', ARRAY['READ', 'UPLOAD_FILES']);
INSERT INTO Groups (name, permissions) VALUES ('group3', ARRAY['READ', 'WRITE', 'DELETE']);
INSERT INTO Groups (name, permissions) VALUES ('group4', ARRAY['READ', 'WRITE', 'DELETE', 'SHARE', 'UPLOAD_FILES']);